---
# handlers file for mapr_drill

- name: reconfigure roles
  sudo: yes
  sudo_user: root
  command: /opt/mapr/server/configure.sh -R

- name: wait a bit
  pause: seconds=10

- name: restart drillbits
  sudo: yes
  sudo_user: "{{mapr_admin_username}}"
  command: maprcli node services -action restart -name drill-bits -nodes {{ansible_fqdn}}
