---
# handlers file for mapr_drill

- name: reconfigure roles
  become: yes
  become_user: root
  command: /opt/mapr/server/configure.sh -R

- name: restart drillbits
  become: yes
  become_user: "{{mapr_admin_username}}"
  command: maprcli node services -action restart -name drill-bits -nodes {{ansible_fqdn}}

- name: add hive storage plugin
  shell: 'curl -H "Content-Type: application/json" -X POST -d @/tmp/hive-storage-plugin.json http://localhost:8047/storage/hive.json'
  run_once: true
